dist: trusty
sudo: false
language: c
compiler: gcc
os: windows

script:
  - mkdir cmake-test
  - cd cmake-test
  - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - MinGW Makefiles" ..
  - cmake --bulid .
  - make