sudo: false
language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
  - windows
arch:
  - amd64
  - arm64

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --bulid .