#ifndef WEBSERVER_C_PLAYGROUND_INTERNALCONFIGURATION_H
#define WEBSERVER_C_PLAYGROUND_INTERNALCONFIGURATION_H

//! Windows default version of socket.
#define DEFAULT_WINDOWS_SOCKET_VERSION MAKEWORD(2,2)

#endif //WEBSERVER_C_PLAYGROUND_INTERNALCONFIGURATION_H
