#ifndef WEBSERVER_C_PLAYGROUND_SERVER_CONFIGURATION_H
#define WEBSERVER_C_PLAYGROUND_SERVER_CONFIGURATION_H

//! @brief Buffer size for receive data from client socket.
enum { SERVER_RECEIVE_BUFFER_SIZE = 0x1000 };

#endif //WEBSERVER_C_PLAYGROUND_SERVER_CONFIGURATION_H
