name: learn-github-actions
on: [push]
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir build
      - run: cd build
      - run: ls ..
      - run: cmake -DCMAKE_BUILD_TYPE=Release ..
      - run: cmake --bulid .
      - run: make
  build-on-osx:
    runs-on: macos-latest
    steps:
      - run: mkdir build
      - run: cd build
      - run: ls ..
      - run: cmake -DCMAKE_BUILD_TYPE=Release ..
      - run: cmake --bulid .
      - run: make
  build-on-windows:
    runs-on: windows-latest
    steps:
      - run: mkdir build
      - run: cd build
      - run: ls ..
      - run: cmake -DCMAKE_BUILD_TYPE=Release ..
      - run: cmake --bulid .
      - run: make